### PR TITLE
Add dream-html package

### PR DESCRIPTION
**Pull request by neshtea**
This pull-request includes a derivation for [yawaramin/dream-html](https://github.com/yawaramin/dream-html).  Since [aantron/dream](https://aantron.github.io/dream/) is already included in this overlay, I've found it useful to include this as well.

### CODE REVIEW

**Review by anmonteiro — COMMENTED** [review]
Should we use the release tag for [1.1.0](https://github.com/yawaramin/dream-html/releases/tag/v1.1.0) or does the rev you added have more fixes?

**Comment by neshtea** [comment]
I thought that was the commit sha of the commit that introduced [1.1.0](https://github.com/yawaramin/dream-html/commit/a0f269f419160cafd8af15bba93c64065b2dad7b).  What am I missing/what should I change it to?

**Comment by anmonteiro** [comment]
> I thought that was the commit sha of the commit that introduced [1.1.0](https://github.com/yawaramin/dream-html/commit/a0f269f419160cafd8af15bba93c64065b2dad7b). What am I missing/what should I change it to?

`rev = “1.1.0”`

**Comment by neshtea** [comment]
> `rev = “1.1.0”`

Thanks for pointing that out, completely slipped my mind as a possibility.

**Comment by anmonteiro** [comment]
Thank you

**Pull request merged**
