### PR TITLE
Format using nixfmt-rfc-style

### PR DESCRIPTION
**Pull request by 0x50F1A**
Since [RFC 0166](https://github.com/NixOS/rfcs/pull/166) is now merged, `pkgs.nixfmt-rfc-style` can format nix files to be conformant.

This has some upsides such as: 

- Formatting matches what consumers might expect if they are coming from nixpkgs 
- Deprecated patterns such as URL literals can be automatically fixed

The latter is relevant to some use cases. 
For example, users on later versions of `nix` or those who set the `no-url-literals` experimental feature cannot evaluate URL literals. 
If a package depends on the OCaml Nix Overlays with these features, it will error out and fail to build.

This merge would format the repository to the RFC 0166 standard using `pkgs.nixfmt-rfc-style` and adopt all the automatic fixes it brings along.

### CODE REVIEW

**Comment by 0x50F1A** [comment]
This was inspired by a real world use case:

Building @faldor20 's https://github.com/faldor20/jj_tui

Will fail to build on versions of Nix that have fully deprecated URL literals due to packages such as `ansi` being declared with a URL literal 

https://github.com/nix-ocaml/nix-overlays/blob/0617ef85a6c5d2417714da23921f54f04e27c685/ocaml/default.nix#L160

An alternative fix could be to do a tree-wide replacement of URL literals with strings containing a URL.

**Comment by anmonteiro** [comment]
Thanks. before I take a closer look, could you point me to more information as to why URL literals were deprecated?

**Comment by 0x50F1A** [comment]
The short of it is here in the [manual](https://nix.dev/manual/nix/2.19/contributing/experimental-features#xp-feature-no-url-literals)

The deprecation was [RFC 0045](https://github.com/NixOS/rfcs/pull/45)

**Comment by anmonteiro** [comment]
This sounds like a good change.

we run `find . -iname '*.nix' | xargs nix shell -f ./ nixpkgs-fmt -c nixpkgs-fmt --check` in CI, though, and it's saying 125/139 files would be reformatted. It might not be related?

**Comment by 0x50F1A** [comment]
`nixpkgs-fmt` and `nixfmt (-rfc-style)` diverge significantly, so that makes sense.

This PR effectively endorses moving from `nixpkgs-fmt` to `nixfmt` to be RFC compliant.

`nixfmt` provides a `nixfmt --check .` which outputs in the following format:

```console
nix-overlays-upstream on master
-> nixfmt --check .

./flake.nix: not formatted
./ci/hydra_jobs.nix: not formatted
./ci/filter.nix: not formatted
./ci/default.nix: not formatted
./ci/hydra.nix: not formatted
./cockroachdb/generic.nix: not formatted
./cockroachdb/default.nix: not formatted
./ocaml/janestreet-0.16.nix: not formatted
./ocaml/overlay-ocaml-packages.nix: not formatted
./ocaml/subscriptions-transport-ws/default.nix: not formatted
./ocaml/piaf/carl.nix: not formatted
./ocaml/piaf/default.nix: not formatted
./ocaml/redis/lwt.nix: not formatted
...
./static/default.nix: not formatted

nix-overlays-upstream on master
->
``` 

Part of this PR could be moving to a more canonical approach such as setting the `formatter` and `check` attributes of the `flake.nix`, and running in CI via `nix check`.

**Comment by anmonteiro** [comment]
> Part of this PR could be moving to a more canonical approach such as setting the `formatter` and `check` attributes of the `flake.nix`, and running in CI via `nix check`.


this sounds good to me. would you do this in a separate PR so that I can better assess the diff?

then we could rebase this one on top, which would just be changing the URL strings

**Comment by anmonteiro** [comment]
https://github.com/nix-ocaml/nix-overlays/pull/1541 changed URLs to plain strings.

Feel free to propose a separate PR changing the formatter.

**Pull request closed without merging**
