### PR TITLE
Update to dune 3.13

### PR DESCRIPTION
**Pull request by emillon**
This updates dune to 3.13.0~alpha1 since your CI tends to catch interesting bugs :)

### CODE REVIEW

**Comment by anmonteiro** [comment]
Thank you! seems like there are no regressions on this end.

**Comment by emillon** [comment]
Good to see. I'll proceed with cutting 3.13.0 which is going to be the same except with a different changelog.

**Comment by emillon** [comment]
Updated to 3.13.0

**Comment by anmonteiro** [comment]
Thanks!

**Pull request merged**
