### PR TITLE
test what will become dune 3.16.1

### PR DESCRIPTION
**Pull request by anmonteiro**

### CODE REVIEW

**Comment by anmonteiro** [comment]
this fails to build because we're on pp 2.0

**Comment by Leonidas-from-XIV** [comment]
@anmonteiro Is there a way to test with an older `pp`?

**Comment by anmonteiro** [comment]
@Leonidas-from-XIV yeah we can do that, I downgraded it just for this PR

**Comment by anmonteiro** [comment]
release seems good from our perspective!

**Pull request closed without merging**
