### PR TITLE
Update dune to 3.15.2

### PR DESCRIPTION
**Pull request by emillon**

### CODE REVIEW

**Comment by anmonteiro** [comment]
hey @emillon, we're in the middle of a big change to github.com/nix-ocaml/nix-ci-build. I predict I'll be able to run this workflow in ~8hours.

**Comment by emillon** [comment]
ok, thanks! I checked ocaml-protoc-plugin locally and it worked fine so I'll go ahead with releasing.

**Comment by emillon** [comment]
(and will update this PR after tagging)

**Comment by anmonteiro** [comment]
Running this now, sorry for the delay.

**Comment by ulrikstrid** [comment]
This has been merged upstream in nixpkgs btw

**Comment by emillon** [comment]
Thanks, I'll close this then.

**Pull request closed without merging**
