### PR TITLE
dune: Update to Dune 3.15~alpha2

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
We decided to make an alpha2 before the release so this updates the definition.

### CODE REVIEW

**Comment by anmonteiro** [comment]
This is looking good now. The only failure happens because the machine runs out of disk space.

**Comment by Leonidas-from-XIV** [comment]
@anmonteiro Excellent, that should bring us closer to a final release. Is there a way to re-run the test so it doesn't run out of disk space? I can of course re-run it but I presume that unless it accidentally runs on a machine with more space it'll fail in the same way.

**Comment by ulrikstrid** [comment]
I can't run it in CI, but I can run it on my Linux machine locally and report back if that's okay

**Comment by anmonteiro** [comment]
> @anmonteiro Excellent, that should bring us closer to a final release. Is there a way to re-run the test so it doesn't run out of disk space? I can of course re-run it but I presume that unless it accidentally runs on a machine with more space it'll fail in the same way.

I can do it in https://github.com/nix-ocaml/nix-overlays/pull/1361 but it'll involve stopping the build half-way to upload to the cache and retrying... It's a bit unfortunate for now, I'm trying to think of solutions for this.

BTW the reason why it won't work on this PR is because external PRs don't have the GH action secrets available in their GH actions runs.

**Comment by anmonteiro** [comment]
https://github.com/nix-ocaml/nix-overlays/pull/1361 has a green build.

**Pull request closed without merging**
