### PR TITLE
use dune 3.16.0

### PR DESCRIPTION
**Pull request by emillon**
(will update PR as release process progresses)

### CODE REVIEW

**Comment by anmonteiro** [comment]
a few issues here

- macOS failures failing to find `<atomic.h>`
- melange broken on 5.2 (what's this new flags `-bin-annot-occurrences`?)

**Comment by anmonteiro** [comment]
> * the atomic failures do happen on dune 3.15.3 don't they? in that case that's an issue with how 5.2 is built on nix

I don’t remember, but 5.2 has been supported for a while; why would it be a packaging bug when the dune upgrade introduced it?

**Comment by anmonteiro** [comment]
> > * the atomic failures do happen on dune 3.15.3 don't they? in that case that's an issue with how 5.2 is built on nix
> 
> I don’t remember, but 5.2 has been supported for a while; why would it be a packaging bug when the dune upgrade introduced it?

ah I see it in other places, too. I think it's minisat that's badly packaged upstream.

**Comment by anmonteiro** [comment]
This now works after having released Melange 4.0.1-52 with support for `-bin-annot-occurrences`.

**Review by anmonteiro — APPROVED** [review]

**Comment by emillon** [comment]
great, thanks. I'm keeping this open to test the next alpha.

**Pull request merged**
